(function(){var l,h,r,v,s,t,q,y,w,z,f,n=[].slice,c=[].indexOf||function(d){for(var a=0,b=this.length;a<b;a++)if(a in this&&this[a]===d)return a;return-1},x={}.hasOwnProperty,e=function(d,a){function b(){this.constructor=d}for(var k in a)x.call(a,k)&&(d[k]=a[k]);b.prototype=a.prototype;d.prototype=new b;d.__super__=a.prototype;return d},A=function(d,a){return function(){return d.apply(a,arguments)}};r={bind:function(d,a){var b,k,m,g,p;k=d.split(" ");b=this.hasOwnProperty("_callbacks")&&this._callbacks||
(this._callbacks={});g=0;for(p=k.length;g<p;g++)m=k[g],b[m]||(b[m]=[]),b[m].push(a);return this},one:function(d,a){var b;return this.bind(d,b=function(){this.unbind(d,b);return a.apply(this,arguments)})},trigger:function(){var d,a,b,k,m;d=1<=arguments.length?n.call(arguments,0):[];b=d.shift();if(b=this.hasOwnProperty("_callbacks")&&(null!=(a=this._callbacks)?a[b]:void 0)){k=0;for(m=b.length;k<m&&(a=b[k],!1!==a.apply(this,d));k++);return!0}},listenTo:function(d,a,b){d.bind(a,b);this.listeningTo||(this.listeningTo=
[]);this.listeningTo.push({obj:d,ev:a,callback:b});return this},listenToOnce:function(d,a,b){var k,m;m=this.listeningToOnce||(this.listeningToOnce=[]);d.bind(a,k=function(){var g,p,u,c,e;p=-1;g=c=0;for(e=m.length;c<e;g=++c)u=m[g],u.obj===d&&u.ev===a&&u.callback===b&&(p=g);d.unbind(a,k);-1!==p&&m.splice(p,1);return b.apply(this,arguments)});m.push({obj:d,ev:a,callback:b,handler:k});return this},stopListening:function(d,a,b){var k,m,g,p,u,c,e,f,h,n,x;if(0===arguments.length){x=[this.listeningTo,this.listeningToOnce];
e=0;for(h=x.length;e<h;e++)if(u=x[e])for(f=0,n=u.length;f<n;f++)c=u[f],c.obj.unbind(c.ev,c.handler||c.callback);return this.listeningToOnce=this.listeningTo=void 0}if(d){h=[this.listeningTo,this.listeningToOnce];n=[];e=0;for(f=h.length;e<f;e++)if(u=h[e])a=a?a.split(" "):[void 0],n.push(function(){var b,d,e;e=[];b=0;for(d=a.length;b<d;b++)k=a[b],e.push(function(){var b,a,d;d=[];for(p=b=a=u.length-1;0>=a?0>=b:0<=b;p=0>=a?++b:--b)c=u[p],k&&k!==c.ev?k?(m=c.ev.split(" "),~(g=m.indexOf(k))?(m.splice(g,
1),c.ev=l.trim(m.join(" ")),d.push(c.obj.unbind(k,c.handler||c.callback))):d.push(void 0)):d.push(void 0):(c.obj.unbind(c.ev,c.handler||c.callback),-1!==p?d.push(u.splice(p,1)):d.push(void 0));return d}());return e}());return n}},unbind:function(d,a){var b,k,m,g,p,c,e,f,h,n;if(0===arguments.length)return this._callbacks={},this;if(!d)return this;k=d.split(" ");c=0;for(f=k.length;c<f;c++)if(p=k[c],g=null!=(n=this._callbacks)?n[p]:void 0)if(a)for(m=e=0,h=g.length;e<h;m=++e){if(b=g[m],b===a){g=g.slice();
g.splice(m,1);this._callbacks[p]=g;break}}else delete this._callbacks[p];return this}};r.on=r.bind;r.off=r.unbind;v={trace:!0,logPrefix:"(App)",log:function(){var c;c=1<=arguments.length?n.call(arguments,0):[];if(this.trace)return this.logPrefix&&c.unshift(this.logPrefix),"undefined"!==typeof console&&null!==console&&"function"===typeof console.log&&console.log.apply(console,c),this}};f=["included","extended"];t=function(){function d(){"function"===typeof this.init&&this.init.apply(this,arguments)}
d.include=function(a){var b,k,m;if(!a)throw Error("include(obj) requires obj");for(b in a)k=a[b],0>c.call(f,b)&&(this.prototype[b]=k);null!=(m=a.included)&&m.apply(this);return this};d.extend=function(a){var b,k,m;if(!a)throw Error("extend(obj) requires obj");for(b in a)k=a[b],0>c.call(f,b)&&(this[b]=k);null!=(m=a.extended)&&m.apply(this);return this};d.proxy=function(a){var b=this;return function(){return a.apply(b,arguments)}};d.prototype.proxy=function(a){var b=this;return function(){return a.apply(b,
arguments)}};return d}();s=function(c){function a(b){a.__super__.constructor.apply(this,arguments);b&&this.load(b);this.cid=(null!=b?b.cid:void 0)||this.constructor.uid("c-")}e(a,c);a.extend(r);a.records=[];a.irecords={};a.attributes=[];a.configure=function(){var b,k;k=arguments[0];b=2<=arguments.length?n.call(arguments,1):[];this.className=k;this.deleteAll();b.length&&(this.attributes=b);this.attributes&&(this.attributes=z(this.attributes));this.attributes||(this.attributes=[]);this.unbind();return this};
a.toString=function(){return""+this.className+"("+this.attributes.join(", ")+")"};a.find=function(b){var k;k=this.exists(b);if(!k)throw Error('"'+this.className+'" model could not find a record for the ID "'+b+'"');return k};a.exists=function(b){var k;return null!=(k=this.irecords[b])?k.clone():void 0};a.addRecord=function(b){b.id&&this.irecords[b.id]&&this.irecords[b.id].remove();b.id||(b.id=b.cid);this.records.push(b);this.irecords[b.id]=b;return this.irecords[b.cid]=b};a.refresh=function(b,k){var a,
g,c,d;null==k&&(k={});k.clear&&this.deleteAll();g=this.fromJSON(b);w(g)||(g=[g]);c=0;for(d=g.length;c<d;c++)a=g[c],this.addRecord(a);this.sort();a=this.cloneArray(g);this.trigger("refresh",a,k);return a};a.select=function(b){var k,a,g,c,d;c=this.records;d=[];a=0;for(g=c.length;a<g;a++)k=c[a],b(k)&&d.push(k.clone());return d};a.findByAttribute=function(b,k){var a,g,c,d;d=this.records;g=0;for(c=d.length;g<c;g++)if(a=d[g],a[b]===k)return a.clone();return null};a.findAllByAttribute=function(b,k){return this.select(function(a){return a[b]===
k})};a.each=function(b){var k,a,g,c,d;c=this.records;d=[];a=0;for(g=c.length;a<g;a++)k=c[a],d.push(b(k.clone()));return d};a.all=function(){return this.cloneArray(this.records)};a.first=function(){var b;return null!=(b=this.records[0])?b.clone():void 0};a.last=function(){var b;return null!=(b=this.records[this.records.length-1])?b.clone():void 0};a.count=function(){return this.records.length};a.deleteAll=function(){this.records=[];return this.irecords={}};a.destroyAll=function(b){var k,a,g,c,d;c=
this.records;d=[];a=0;for(g=c.length;a<g;a++)k=c[a],d.push(k.destroy(b));return d};a.update=function(b,a,c){return this.find(b).updateAttributes(a,c)};a.create=function(b,a){return(new this(b)).save(a)};a.destroy=function(b,a){return this.find(b).destroy(a)};a.change=function(b){return"function"===typeof b?this.bind("change",b):this.trigger.apply(this,["change"].concat(n.call(arguments)))};a.fetch=function(b){return"function"===typeof b?this.bind("fetch",b):this.trigger.apply(this,["fetch"].concat(n.call(arguments)))};
a.toJSON=function(){return this.records};a.fromJSON=function(b){var a,c,g,d;if(b){"string"===typeof b&&(b=JSON.parse(b));if(w(b)){d=[];c=0;for(g=b.length;c<g;c++)a=b[c],d.push(new this(a));return d}return new this(b)}};a.fromForm=function(){var b;return(b=new this).fromForm.apply(b,arguments)};a.sort=function(){this.comparator&&this.records.sort(this.comparator);return this};a.cloneArray=function(b){var a,c,g,d;d=[];c=0;for(g=b.length;c<g;c++)a=b[c],d.push(a.clone());return d};a.idCounter=0;a.uid=
function(b){var a;null==b&&(b="");a=b+this.idCounter++;this.exists(a)&&(a=this.uid(b));return a};a.prototype.isNew=function(){return!this.exists()};a.prototype.isValid=function(){return!this.validate()};a.prototype.validate=function(){};a.prototype.load=function(b){var a,c;b.id&&(this.id=b.id);for(a in b)if(c=b[a],b.hasOwnProperty(a)&&"function"===typeof this[a])this[a](c);else this[a]=c;return this};a.prototype.attributes=function(){var b,a,c,g,d;a={};d=this.constructor.attributes;c=0;for(g=d.length;c<
g;c++)b=d[c],b in this&&(a[b]="function"===typeof this[b]?this[b]():this[b]);this.id&&(a.id=this.id);return a};a.prototype.eql=function(b){return!!(b&&b.constructor===this.constructor&&b.cid===this.cid||b.id&&b.id===this.id)};a.prototype.save=function(b){var a;null==b&&(b={});if(!1!==b.validate&&(a=this.validate()))return this.trigger("error",a),!1;this.trigger("beforeSave",b);a=this.isNew()?this.create(b):this.update(b);this.stripCloneAttrs();this.trigger("save",b);return a};a.prototype.stripCloneAttrs=
function(){var b;if(!this.hasOwnProperty("cid")){for(b in this)x.call(this,b)&&-1<this.constructor.attributes.indexOf(b)&&delete this[b];return this}};a.prototype.updateAttribute=function(b,a,c){var g;g={};g[b]=a;return this.updateAttributes(g,c)};a.prototype.updateAttributes=function(b,a){this.load(b);return this.save(a)};a.prototype.changeID=function(b){var a;if(b!==this.id)return a=this.constructor.irecords,a[b]=a[this.id],delete a[this.id],this.id=b,this.save()};a.prototype.remove=function(){var b,
a,c,g,d;c=this.constructor.records.slice(0);b=g=0;for(d=c.length;g<d;b=++g)if(a=c[b],this.eql(a)){c.splice(b,1);break}this.constructor.records=c;delete this.constructor.irecords[this.id];return delete this.constructor.irecords[this.cid]};a.prototype.destroy=function(b){null==b&&(b={});this.trigger("beforeDestroy",b);this.remove();this.destroyed=!0;this.trigger("destroy",b);this.trigger("change","destroy",b);this.listeningTo&&this.stopListening();this.unbind();return this};a.prototype.dup=function(b){var a;
null==b&&(b=!0);a=this.attributes();b?delete a.id:a.cid=this.cid;return new this.constructor(a)};a.prototype.clone=function(){return y(this)};a.prototype.reload=function(){var b;if(this.isNew())return this;b=this.constructor.find(this.id);this.load(b.attributes());return b};a.prototype.refresh=function(b){this.constructor.irecords[this.id].load(b);this.trigger("refresh");return this};a.prototype.toJSON=function(){return this.attributes()};a.prototype.toString=function(){return"<"+this.constructor.className+
" ("+JSON.stringify(this)+")>"};a.prototype.fromForm=function(b){var a,c,g,d,e,f,h;g={};e=l(b).find("[type=checkbox]:not([value])");c=0;for(d=e.length;c<d;c++)a=e[c],g[a.name]=l(a).prop("checked");h=l(b).find('[type=checkbox][name$="[]"]');d=0;for(e=h.length;d<e;d++)a=h[d],c=a.name.replace(/\[\]$/,""),g[c]||(g[c]=[]),l(a).prop("checked")&&g[c].push(a.value);d=l(b).serializeArray();a=0;for(c=d.length;a<c;a++)b=d[a],g[f=b.name]||(g[f]=b.value);return this.load(g)};a.prototype.exists=function(){return this.constructor.exists(this.id)};
a.prototype.update=function(b){var a;this.trigger("beforeUpdate",b);a=this.constructor.irecords;a[this.id].load(this.attributes());this.constructor.sort();a=a[this.id].clone();a.trigger("update",b);a.trigger("change","update",b);return a};a.prototype.create=function(b){var a;this.trigger("beforeCreate",b);this.id||(this.id=this.cid);a=this.dup(!1);this.constructor.addRecord(a);this.constructor.sort();a=a.clone();a.trigger("create",b);a.trigger("change","create",b);return a};a.prototype.bind=function(b,
a){var c,d,e,f,h,n,l=this;this.constructor.bind(b,c=function(b){if(b&&l.eql(b))return a.apply(l,arguments)});n=b.split(" ");e=function(b){var d;return l.constructor.bind("unbind",d=function(g,e,f){if(!(!g||!l.eql(g)||e&&e!==b||f&&f!==a))return l.constructor.unbind(b,c),l.constructor.unbind("unbind",d)})};f=0;for(h=n.length;f<h;f++)d=n[f],e(d);return this};a.prototype.one=function(b,a){var c,d=this;return this.bind(b,c=function(){d.unbind(b,c);return a.apply(d,arguments)})};a.prototype.trigger=function(){var b,
a;b=1<=arguments.length?n.call(arguments,0):[];b.splice(1,0,this);return(a=this.constructor).trigger.apply(a,b)};a.prototype.listenTo=function(){return r.listenTo.apply(this,arguments)};a.prototype.listenToOnce=function(){return r.listenToOnce.apply(this,arguments)};a.prototype.stopListening=function(){return r.stopListening.apply(this,arguments)};a.prototype.unbind=function(b,a){var c,d,e,f,h;if(0===arguments.length)return this.trigger("unbind");if(b){f=b.split(" ");h=[];d=0;for(e=f.length;d<e;d++)c=
f[d],h.push(this.trigger("unbind",c,a));return h}};return a}(t);s.prototype.on=s.prototype.bind;s.prototype.off=s.prototype.unbind;h=function(c){function a(b){this.release=A(this.release,this);var c,d,g;g=this.options=b;for(c in g)d=g[c],this[c]=d;this.el||(this.el=document.createElement(this.tag));this.$el=this.el=l(this.el);this.className&&this.el.addClass(this.className);this.attributes&&this.el.attr(this.attributes);this.events||(this.events=this.constructor.events);this.elements||(this.elements=
this.constructor.elements);for(c=this;c=c.constructor.__super__;)c.events&&(this.events=l.extend({},c.events,this.events)),c.elements&&(this.elements=l.extend({},c.elements,this.elements));this.events&&this.delegateEvents(this.events);this.elements&&this.refreshElements();a.__super__.constructor.apply(this,arguments)}e(a,c);a.include(r);a.include(v);a.prototype.eventSplitter=/^(\S+)\s*(.*)$/;a.prototype.tag="div";a.prototype.release=function(){this.trigger("release",this);this.el.remove();this.unbind();
return this.stopListening()};a.prototype.$=function(b){return l(b,this.el)};a.prototype.delegateEvents=function(b){var a,c,d,e,f,h=this;f=[];for(c in b){e=b[c];if("function"===typeof e)e=function(a){return function(){a.apply(h,arguments);return!0}}(e);else{if(!this[e])throw Error(""+e+" doesn't exist");e=function(a){return function(){h[a].apply(h,arguments);return!0}}(e)}d=c.match(this.eventSplitter);a=d[1];d=d[2];""===d?f.push(this.el.bind(a,e)):f.push(this.el.on(a,d,e))}return f};a.prototype.refreshElements=
function(){var a,c,d,g;d=this.elements;g=[];for(a in d)c=d[a],g.push(this[c]=this.$(a));return g};a.prototype.delay=function(a,c){return setTimeout(this.proxy(a),c||0)};a.prototype.html=function(a){this.el.html(a.el||a);this.refreshElements();return this.el};a.prototype.append=function(){var a,c,d;c=1<=arguments.length?n.call(arguments,0):[];var g,e,f;f=[];g=0;for(e=c.length;g<e;g++)a=c[g],f.push(a.el||a);(d=this.el).append.apply(d,f);this.refreshElements();return this.el};a.prototype.appendTo=function(a){this.el.appendTo(a.el||
a);this.refreshElements();return this.el};a.prototype.prepend=function(){var a,c,d;c=1<=arguments.length?n.call(arguments,0):[];var g,e,f;f=[];g=0;for(e=c.length;g<e;g++)a=c[g],f.push(a.el||a);(d=this.el).prepend.apply(d,f);this.refreshElements();return this.el};a.prototype.replace=function(a){var c;a=a.el||a;"string"===typeof a&&(a=l.trim(a));a=[this.el,l((null!=(c=l.parseHTML(a))?c[0]:void 0)||a)];c=a[0];this.el=a[1];c.replaceWith(this.el);this.delegateEvents(this.events);this.refreshElements();
return this.el};return a}(t);l=("undefined"!==typeof window&&null!==window?window.jQuery:void 0)||("undefined"!==typeof window&&null!==window?window.Zepto:void 0)||function(c){return c};y=Object.create||function(c){var a;a=function(){};a.prototype=c;return new a};w=function(c){return"[object Array]"===Object.prototype.toString.call(c)};z=function(c){return Array.prototype.slice.call(c,0)};q=this.Spine={};"undefined"!==typeof module&&null!==module&&(module.exports=q);q.version="1.2.0";q.isArray=w;
q.isBlank=function(c){var a;if(!c)return!0;for(a in c)return!1;return!0};q.$=l;q.Events=r;q.Log=v;q.Module=t;q.Controller=h;q.Model=s;t.extend.call(q,r);t.create=t.sub=h.create=h.sub=s.sub=function(c,a){var b,f;b=function(a){function b(){return f=b.__super__.constructor.apply(this,arguments)}e(b,a);return b}(this);c&&b.include(c);a&&b.extend(a);"function"===typeof b.unbind&&b.unbind();return b};s.setup=function(c,a){var b,f;null==a&&(a=[]);b=function(a){function b(){return f=b.__super__.constructor.apply(this,
arguments)}e(b,a);return b}(this);b.configure.apply(b,[c].concat(n.call(a)));return b};q.Class=t}).call(this);
(function(){var l,h,r,v,s,t,q={}.hasOwnProperty,y=function(h,f){function n(){this.constructor=h}for(var c in f)q.call(f,c)&&(h[c]=f[c]);n.prototype=f.prototype;h.prototype=new n;h.__super__=f.prototype;return h},w=[].slice;h=this.Spine||require("spine");l=h.$;v=/^#*/;s=/:([\w\d]+)/g;t=/\*([\w\d]+)/g;r=/[-[\]{}()+?.,\\^$|#\s]/g;h.Route=function(q){function f(c,f){var e;this.path=c;this.callback=f;this.names=[];if("string"===typeof c){for(s.lastIndex=0;null!==(e=s.exec(c));)this.names.push(e[1]);for(t.lastIndex=
0;null!==(e=t.exec(c));)this.names.push(e[1]);c=c.replace(r,"\\$&").replace(s,"([^/]*)").replace(t,"(.*?)");this.route=RegExp("^"+c+"$")}else this.route=c}var n;y(f,q);f.extend(h.Events);f.historySupport=null!=(null!=(n=window.history)?n.pushState:void 0);f.routes=[];f.options={trigger:!0,history:!1,shim:!1,replace:!1,redirect:!1};f.add=function(c,f){var e,h,d;if("object"!==typeof c||c instanceof RegExp)return this.routes.push(new this(c,f));d=[];for(e in c)h=c[e],d.push(this.add(e,h));return d};
f.setup=function(c){null==c&&(c={});this.options=l.extend({},this.options,c);this.options.history&&(this.history=this.historySupport&&this.options.history);if(!this.options.shim)return this.history?l(window).bind("popstate",this.change):l(window).bind("hashchange",this.change),this.change()};f.unbind=function(){if(!this.options.shim)return this.history?l(window).unbind("popstate",this.change):l(window).unbind("hashchange",this.change)};f.navigate=function(){var c,f,e,h;c=1<=arguments.length?w.call(arguments,
0):[];e={};f=c[c.length-1];"object"===typeof f?e=c.pop():"boolean"===typeof f&&(e.trigger=c.pop());e=l.extend({},this.options,e);c=c.join("/");if(this.path!==c&&(this.path=c,this.trigger("navigate",this.path),e.trigger&&(h=this.matchRoute(this.path,e)),!e.shim)){if(!h){if("function"===typeof e.redirect)return e.redirect.apply(this,[this.path,e]);!0===e.redirect&&this.redirect(this.path)}return this.history&&e.replace?history.replaceState({},document.title,this.path):this.history?history.pushState({},
document.title,this.path):window.location.hash=this.path}};f.getPath=function(){var c;this.history?(c=window.location.pathname,"/"!==c.substr(0,1)&&(c="/"+c)):(c=window.location.hash,c=c.replace(v,""));return c};f.getHost=function(){return""+window.location.protocol+"//"+window.location.host};f.change=function(){var c;c=this.getPath();if(c!==this.path)return this.path=c,this.matchRoute(this.path)};f.matchRoute=function(c,f){var e,h,d,a;a=this.routes;h=0;for(d=a.length;h<d;h++)if(e=a[h],e.match(c,
f))return this.trigger("change",e,c),e};f.redirect=function(c){return window.location=c};f.prototype.match=function(c,f){var e,h,d,a,b;null==f&&(f={});e=this.route.exec(c);if(!e)return!1;f.match=e;d=e.slice(1);if(this.names.length)for(e=a=0,b=d.length;a<b;e=++a)h=d[e],f[this.names[e]]=h;return!1!==this.callback.call(null,f)};return f}(h.Module);h.Route.change=h.Route.proxy(h.Route.change);h.Controller.include({route:function(l,f){return h.Route.add(l,this.proxy(f))},routes:function(h){var f,l,c;c=
[];for(f in h)l=h[f],c.push(this.route(f,l));return c},navigate:function(){return h.Route.navigate.apply(h.Route,arguments)}});"undefined"!==typeof module&&null!==module&&(module.exports=h.Route)}).call(this);